# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maze.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

class MazeDialog(QtCore.QObject):
    """ Maze Configuration Dialog """

    applySignal = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super(QtCore.QObject, self).__init__(parent)
        self.maze = None

    def setupUi(self, Dialog):

        Dialog.setObjectName("Maze Configuration")
        Dialog.resize(357, 202)

        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel |
                                          QtWidgets.QDialogButtonBox.Ok |
                                          QtWidgets.QDialogButtonBox.Apply)
        self.buttonBox.setObjectName("buttonBox")

        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # Number of cells

        self.horizontalLayoutMazeCells = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMazeCells.setObjectName(
            "horizontalLayoutMazeCells")
        self.labelMazeCells = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelMazeCells.sizePolicy().hasHeightForWidth())
        self.labelMazeCells.setSizePolicy(sizePolicy)
        self.labelMazeCells.setMinimumSize(QtCore.QSize(160, 0))
        self.labelMazeCells.setObjectName("labelMazeCells")
        self.horizontalLayoutMazeCells.addWidget(self.labelMazeCells)
        self.spinHCells = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinHCells.sizePolicy().hasHeightForWidth())
        self.spinHCells.setSizePolicy(sizePolicy)
        self.spinHCells.setMinimum(3)
        self.spinHCells.setMaximum(32)
        self.spinHCells.setProperty("value", 8)
        self.spinHCells.setObjectName("spinHCells")
        self.horizontalLayoutMazeCells.addWidget(self.spinHCells)
        self.labelXMazeCells = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelXMazeCells.sizePolicy().hasHeightForWidth())
        self.labelXMazeCells.setSizePolicy(sizePolicy)
        self.labelXMazeCells.setObjectName("labelXMazeCells")
        self.horizontalLayoutMazeCells.addWidget(self.labelXMazeCells)
        self.spinVCells = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinVCells.sizePolicy().hasHeightForWidth())
        self.spinVCells.setSizePolicy(sizePolicy)
        self.spinVCells.setMinimum(3)
        self.spinVCells.setMaximum(32)
        self.spinVCells.setProperty("value", 6)
        self.spinVCells.setObjectName("spinVCells")
        self.horizontalLayoutMazeCells.addWidget(self.spinVCells)
        self.verticalLayout.addLayout(self.horizontalLayoutMazeCells)

        # Cell Size

        self.horizontalLayoutCellSize = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCellSize.setObjectName("horizontalLayoutCellSize")
        self.labelCellSize = QtWidgets.QLabel(self.frame)
        self.labelCellSize.setMinimumSize(QtCore.QSize(160, 0))
        self.labelCellSize.setObjectName("labelCellSize")
        self.horizontalLayoutCellSize.addWidget(self.labelCellSize)
        self.spinCellX = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinCellX.sizePolicy().hasHeightForWidth())
        self.spinCellX.setSizePolicy(sizePolicy)
        self.spinCellX.setMinimum(4)
        self.spinCellX.setMaximum(64)
        self.spinCellX.setProperty("value", 15)
        self.spinCellX.setObjectName("spinCellX")
        self.horizontalLayoutCellSize.addWidget(self.spinCellX)
        self.labelXCellSize = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelXCellSize.sizePolicy().hasHeightForWidth())
        self.labelXCellSize.setSizePolicy(sizePolicy)
        self.labelXCellSize.setObjectName("labelXCellSize")
        self.horizontalLayoutCellSize.addWidget(self.labelXCellSize)
        self.spinCellY = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinCellY.sizePolicy().hasHeightForWidth())
        self.spinCellY.setSizePolicy(sizePolicy)
        self.spinCellY.setMinimum(4)
        self.spinCellY.setMaximum(64)
        self.spinCellY.setProperty("value", 15)
        self.spinCellY.setObjectName("spinCellY")
        self.horizontalLayoutCellSize.addWidget(self.spinCellY)
        self.verticalLayout.addLayout(self.horizontalLayoutCellSize)

        # Start Cell
        
        self.horizontalLayoutStart = QtWidgets.QHBoxLayout()
        self.horizontalLayoutStart.setObjectName("horizontalLayoutStart")
        self.labelStartCell = QtWidgets.QLabel(self.frame)
        self.labelStartCell.setMinimumSize(QtCore.QSize(160, 0))
        self.labelStartCell.setObjectName("labelStartCell")
        self.horizontalLayoutStart.addWidget(self.labelStartCell)
        self.spinStartX = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinStartX.sizePolicy().hasHeightForWidth())
        self.spinStartX.setSizePolicy(sizePolicy)
        self.spinStartX.setObjectName("spinStartX")
        self.horizontalLayoutStart.addWidget(self.spinStartX)
        self.labelStartX = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelStartX.sizePolicy().hasHeightForWidth())
        self.labelStartX.setSizePolicy(sizePolicy)
        self.labelStartX.setObjectName("labelStartX")
        self.horizontalLayoutStart.addWidget(self.labelStartX)
        self.spinStartY = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinStartY.sizePolicy().hasHeightForWidth())
        self.spinStartY.setSizePolicy(sizePolicy)
        self.spinStartY.setObjectName("spinStartY")
        self.horizontalLayoutStart.addWidget(self.spinStartY)
        self.verticalLayout.addLayout(self.horizontalLayoutStart)

        # Finish Cell

        self.horizontalLayoutFinish = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFinish.setObjectName("horizontalLayoutFinish")
        self.labelFinishCell = QtWidgets.QLabel(self.frame)
        self.labelFinishCell.setMinimumSize(QtCore.QSize(160, 0))
        self.labelFinishCell.setObjectName("labelFinishCell")
        self.horizontalLayoutFinish.addWidget(self.labelFinishCell)
        self.spinFinishX = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinFinishX.sizePolicy().hasHeightForWidth())
        self.spinFinishX.setSizePolicy(sizePolicy)
        self.spinFinishX.setObjectName("spinFinishX")
        self.horizontalLayoutFinish.addWidget(self.spinFinishX)
        self.labelFinishX = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelFinishX.sizePolicy().hasHeightForWidth())
        self.labelFinishX.setSizePolicy(sizePolicy)
        self.labelFinishX.setObjectName("labelFinishX")
        self.horizontalLayoutFinish.addWidget(self.labelFinishX)
        self.spinFinishY = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinFinishY.sizePolicy().hasHeightForWidth())
        self.spinFinishY.setSizePolicy(sizePolicy)
        self.spinFinishY.setObjectName("spinFinishY")
        self.horizontalLayoutFinish.addWidget(self.spinFinishY)
        self.verticalLayout.addLayout(self.horizontalLayoutFinish)

        # Cycles

        self.horizontalLayoutCycles = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCycles.setObjectName(
            "horizontalLayoutCycles")
        self.labelCycles = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelCycles.sizePolicy().hasHeightForWidth())
        self.labelCycles.setSizePolicy(sizePolicy)
        self.labelCycles.setMinimumSize(QtCore.QSize(160, 0))
        self.labelCycles.setObjectName("labelCycles")
        self.horizontalLayoutCycles.addWidget(self.labelCycles)
        self.spinCycles = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.spinCycles.sizePolicy().hasHeightForWidth())
        self.spinCycles.setSizePolicy(sizePolicy)
        self.spinCycles.setMinimum(0)
        self.spinCycles.setMaximum(32)
        self.spinCycles.setProperty("value", 0)
        self.spinCycles.setObjectName("spinCycles")
        self.horizontalLayoutCycles.addWidget(self.spinCycles)
        self.verticalLayout.addLayout(self.horizontalLayoutCycles)

        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.parentAccept = Dialog.accept
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Apply).clicked.\
            connect(self.applyChanges)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelMazeCells.setText(_translate("Dialog",
                                               "Maze cells (width x height):"))
        self.labelXMazeCells.setText(_translate("Dialog", "x"))
        self.labelCellSize.setText(_translate("Dialog",
                                              "Cell size (width x height):"))
        self.labelXCellSize.setText(_translate("Dialog", "x"))
        self.labelStartCell.setText(_translate("Dialog",
                                               "Starting cell"))
        self.labelStartX.setText(_translate("Dialog", "x"))
        self.labelFinishCell.setText(_translate("Dialog",
                                                "Finish cell"))
        self.labelFinishX.setText(_translate("Dialog", "x"))
        self.labelCycles.setText(_translate("Dialog", "Cycles"))

    def exportValues(self):
        """Copy the values from the GUI into the maze structure"""
        self.maze.nx = self.spinHCells.value()
        self.maze.ny = self.spinVCells.value()

        self.maze.cellSizeX = self.spinCellX.value()
        self.maze.cellSizeY = self.spinCellY.value()

        self.maze.startX = min(self.maze.nx-1,
                               max(0, self.spinStartX.value()))
        self.maze.startY = min(self.maze.ny-1,
                               max(0, self.spinStartY.value()))

        self.maze.endX = min(self.maze.nx-1,
                             max(0, self.spinFinishX.value()))
        self.maze.endY = min(self.maze.ny-1,
                             max(0, self.spinFinishY.value()))
        self.maze.cycles = max(0, self.spinCycles.value())

    def accept(self):
        print("[DBG] Accepting new values")
        self.exportValues()
        self.parentAccept()

    def applyChanges(self):
        print("[DBG] Applying new values")
        self.exportValues()
        self.applySignal.emit()

    def setValues(self, theMaze):
        """ Copy the data from the maze into the dialog settings"""

        print("[DBG] Setting current values into the dialog")
        self.maze = theMaze
        self.spinHCells.setValue(self.maze.nx)
        self.spinVCells.setValue(self.maze.ny)
        self.spinCellX.setValue(self.maze.cellSizeX)
        self.spinCellY.setValue(self.maze.cellSizeY)
        self.spinStartX.setValue(self.maze.startX)
        self.spinStartY.setValue(self.maze.startY)
        self.spinFinishX.setValue(self.maze.endX)
        self.spinFinishY.setValue(self.maze.endY)
        self.spinCycles.setValue(self.maze.cycles)
